name: CSS Validation

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'assets/**/*.css'

jobs:
  validate_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate CSS files
        run: |
          css_files=$(find assets -name '*.css')
          for file in $css_files; do
            if ! npx stylelint "$file"; then
              echo "Invalid CSS syntax in file $file"
              exit 1
            fi
          done
