name: JSON Validation

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'assets/**.json'

jobs:
  validate_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate JSON files
        run: |
          json_files=$(find assets -name '*.json')
          for file in $json_files; do
            if ! jq . "$file" >/dev/null 2>&1; then
              echo "Invalid JSON in file $file"
              exit 1
            fi
          done
